DOTFILES=$HOME/dotfiles
source $DOTFILES/antigen/antigen.zsh

antigen bundle ssh-agent
antigen bundle sublime
antigen use oh-my-zsh

antigen theme $DOTFILES/zsh/james.zsh-theme --no-local-clone

DISABLE_CORRECTION="true"

source $DOTFILES/tmuxinator/tmuxinator.zsh

export EDITOR='atom'

if [[ -d $HOME/Desktop/gambit ]]; then
    PATH=$PATH:$HOME/Desktop/gambit
fi

if [[ -d $HOME/Projects/sage-game-theory ]]; then
    export PATH=$PATH:~/Projects/sage-game-theory
fi

if which pyenv > /dev/null; then
    eval "$(pyenv init -)";
fi

if which pyenv-virtualenv-init > /dev/null; then
    eval "$(pyenv virtualenv-init -)";
fi
setopt AUTO_CD

antigen apply
