DOTFILES=$HOME/dotfiles
source $DOTFILES/antigen/antigen.zsh

antigen bundle sublime
antigen use oh-my-zsh

antigen theme $DOTFILES/zsh/james.zsh-theme --no-local-clone

DISABLE_CORRECTION="true"

if [ "$(uname)" = "Darwin" ]; then
	export EDITOR='sublime'
	antigen bundle brew
	antigen bundle osx
	bindkey -e
	bindkey '^[[1;9C' forward-word
	bindkey '^[[1;9D' backward-word
fi

if [ "$(uname)" != "Darwin" ]; then
	antigen bundle ssh-agent
fi

if [[ -d $HOME/Desktop/gambit ]]; then
    PATH=$PATH:$HOME/Desktop/gambit
fi

if [[ -d $HOME/Projects/sage-game-theory ]]; then
    export PATH=$PATH:~/Projects/sage-game-theory
fi

if which pyenv > /dev/null; then
    eval "$(pyenv init -)";
fi

if which pyenv-virtualenv-init > /dev/null; then
    eval "$(pyenv virtualenv-init -)";
fi
setopt AUTO_CD

antigen apply
